model:
  name: model_2
  parameters:
    embedding_dim: 128
    num_layers: 2

optimizer:
  lr: 1.0e-4

vocabulary:
#  captions_file_path: "/Users/teapula/Documents/AIM/DeepLearning/image_captioning/flickr8k/vocabulary_captions.txt"
  captions_file_path: "/storage/homefs/tp23a087/image_captioning/flickr8k/vocabulary_captions.txt"

data:
  train:
#    images_folder_path: "/Users/teapula/Documents/AIM/DeepLearning/image_captioning/flickr8k/train_images"
#    captions_file_path: "/Users/teapula/Documents/AIM/DeepLearning/image_captioning/flickr8k/train_captions.txt"
    images_folder_path: "/storage/homefs/tp23a087/image_captioning/flickr8k/train_images"
    captions_file_path: "/storage/homefs/tp23a087/image_captioning/flickr8k/train_captions.txt"
    batch_size: 512
  val:
#    images_folder_path: "/Users/teapula/Documents/AIM/DeepLearning/image_captioning/flickr8k/val_images"
#    captions_file_path: "/Users/teapula/Documents/AIM/DeepLearning/image_captioning/flickr8k/val_captions.txt"
    images_folder_path: "/storage/homefs/tp23a087/image_captioning/flickr8k/val_images"
    captions_file_path: "/storage/homefs/tp23a087/image_captioning/flickr8k/val_captions.txt"
    batch_size: 512
